/**
 * Housing-market metrics from Redfin's public Data Center (generated by
 * `npm run ingest:market`). City-level; CDPs and neighborhoods won't match and
 * simply show nothing. Attribution is required and always displayed.
 */

import marketJson from "./generated/market.json";

export interface MarketMetrics {
  periodEnd: string;
  medianSalePrice: number | null;
  medianSalePriceYoY: number | null; // fraction, e.g. 0.042
  medianDom: number | null;
  homesSold: number | null;
  inventory: number | null;
}

interface MarketFile {
  generatedAt: string | null;
  source: string;
  areas: Record<string, MarketMetrics>;
}

const MARKET: MarketFile = marketJson as unknown as MarketFile;

export interface MarketRow {
  label: string;
  value: string;
}

export function marketRows(areaId: string): { rows: MarketRow[]; source: string; periodEnd: string } | null {
  const m = MARKET.areas[areaId];
  if (!m || m.medianSalePrice == null) return null;
  const rows: MarketRow[] = [
    { label: "Median sale price", value: `$${Math.round(m.medianSalePrice).toLocaleString("en-US")}` },
  ];
  if (m.medianSalePriceYoY != null) {
    const pct = (m.medianSalePriceYoY * 100).toFixed(1);
    rows.push({ label: "Price change (year over year)", value: `${m.medianSalePriceYoY >= 0 ? "+" : ""}${pct}%` });
  }
  if (m.medianDom != null) rows.push({ label: "Median days on market", value: String(Math.round(m.medianDom)) });
  if (m.homesSold != null) rows.push({ label: "Homes sold (month)", value: String(m.homesSold) });
  if (m.inventory != null) rows.push({ label: "Active inventory", value: String(m.inventory) });
  return { rows, source: MARKET.source, periodEnd: m.periodEnd };
}
