/**
 * Lookup for official school outcomes (generated by `npm run ingest:outcomes`).
 * High schools only — that's where cohorts exist; elementary/middle show none.
 */

import outcomesJson from "./generated/school-outcomes.json";
import { outcomeSummary, type SchoolOutcome } from "./school-outcomes";

interface OutcomesFile {
  generatedAt: string | null;
  source: string | null;
  academicYear: string | null;
  stateGradRate: number | null;
  stateUcCsuRate: number | null;
  schools: Record<string, SchoolOutcome>;
}

const OUTCOMES: OutcomesFile = outcomesJson as unknown as OutcomesFile;

export function schoolOutcomeText(cdsCode: string | undefined): string | null {
  if (!cdsCode) return null;
  const o = OUTCOMES.schools[cdsCode];
  if (!o) return null;
  return outcomeSummary(o, OUTCOMES.stateGradRate);
}

export function outcomesSourceLabel(): string | null {
  return OUTCOMES.source;
}
