/**
 * Trajectory data (generated by `npm run ingest:trends`): ACS change over
 * non-overlapping windows + BLS county unemployment. Deterministic,
 * comparison-framed statements — evidence for "up-and-coming", never a verdict.
 */

import trendsJson from "./generated/trends.json";

interface CountyTrend {
  latestRate: number;
  latestPeriod: string;
  yearAgoRate: number | null;
}

interface TrendsFile {
  generatedAt: string | null;
  baselinePeriod: string | null;
  currentPeriod: string | null;
  blsSource: string;
  medianIncomeChangePct: number | null;
  counties: Record<string, CountyTrend>;
  areas: Record<string, { incomeChangePct: number | null; popChangePct: number | null }>;
}

const TRENDS: TrendsFile = trendsJson as unknown as TrendsFile;

const COUNTY_NAME_TO_FIPS: Record<string, string> = {
  "Los Angeles County": "06037",
  "Orange County": "06059",
  "Riverside County": "06065",
  "San Bernardino County": "06071",
  "Ventura County": "06111",
};

const pct = (v: number) => `${v >= 0 ? "+" : ""}${(v * 100).toFixed(0)}%`;

/** "LA County unemployment 5.3% (June 2026), down from 5.6% a year earlier" */
export function countyUnemploymentText(countyName: string): { text: string; source: string } | null {
  const fips = COUNTY_NAME_TO_FIPS[countyName];
  const c = fips ? TRENDS.counties[fips] : undefined;
  if (!c) return null;
  let text = `County unemployment ${c.latestRate.toFixed(1)}% (${c.latestPeriod})`;
  if (c.yearAgoRate != null) {
    const dir = c.latestRate < c.yearAgoRate ? "down from" : c.latestRate > c.yearAgoRate ? "up from" : "unchanged from";
    text += `, ${dir} ${c.yearAgoRate.toFixed(1)}% a year earlier`;
  }
  return { text, source: TRENDS.blsSource };
}

/** Deterministic trajectory statements for a region, vs the regional median. */
export function trajectoryHighlights(regionId: string): string[] {
  const t = TRENDS.areas[regionId];
  if (!t || !TRENDS.baselinePeriod) return [];
  const out: string[] = [];
  if (t.incomeChangePct != null) {
    let s = `Median household income ${t.incomeChangePct >= 0 ? "rose" : "fell"} ${pct(t.incomeChangePct)} between the ${TRENDS.baselinePeriod} and ${TRENDS.currentPeriod} periods`;
    if (TRENDS.medianIncomeChangePct != null) {
      s += ` (regional median ${pct(TRENDS.medianIncomeChangePct)})`;
    }
    out.push(s + ".");
  }
  if (t.popChangePct != null && Math.abs(t.popChangePct) >= 0.05) {
    out.push(
      `Population ${t.popChangePct >= 0 ? "grew" : "declined"} ${pct(t.popChangePct)} over the same span.`
    );
  }
  return out;
}

export function trendPeriods(): { baseline: string | null; current: string | null } {
  return { baseline: TRENDS.baselinePeriod, current: TRENDS.currentPeriod };
}
